# llia.synths.io.io_data

from __future__ import print_function

from llia.program import Program
from llia.bank import ProgramBank
from llia.performance_edit import performance
from llia.util.lmath import coin,rnd,pick

prototype = {
    "amp" : 0.10,
    "vfreq" : 7.0,
    "vlock" : 1,
    "vnoise" : 0.3,
    "vdelay" : 1.0,
    "vsens" : 0.1,
    "vdepth" : 0.0,
    "vibrato" : 0.0,
    "xPitch" : 0.0,
    "tremRatio" : 1.0,
    "noiseRatio" : 1,
    "chiffAttack" : 0.03,
    "chiffDecay" : 0.2,
    "chiffAmp" : 0.05,
    "chiffVelocity" : 0.5,
    "noiseAmp" : 1.0,
    "blipAttack" : 0.03,
    "blipDecay" : 0.1,
    "blipDepth" : 0.0,
    "blipVelocity" : 0.0,
    "op4Ratio" : 1.0,
    "op4Feedback" : 0.0,
    "op4LFO" : 0.0,
}

for op in (1,2,3):
    for p,v in {"op%dFormant" : 300,
                "op%dRatio" : 1.0,
                "op%dMode" : 0,
                "op%dVelocity" : 0.0,
                "op%dTremolo" : 0.0,
                "op%dModDepth" : 1.0,
                "op%dAttack" : 0.05,
                "op%dDecay" : 0.30,
                "op%dSustain" : 0.5,
                "op%dRelease" : 0.1,
                "op%dModLag" : 0.0,
                "op%dBreakKey" : 60,
                "op%dLeftKeyScale" : 0,
                "op%dRightKeyScale" : 0,
                "op%dAmp" : 1.0,
                "op%dX" : 0.0}.items():
        prototype[p%op] = v
   

        

class Io(Program):

    def __init__(self,name):
        super(Io,self).__init__(name,Io,prototype)
        self.performance = performance()

program_bank = ProgramBank(Io("Init"))
program_bank.enable_undo = False

def vibrato(freq = 7.0,
            lock = 1,
            noise = 0.3,
            delay = 0.0,
            sens = 0.1,
            depth = 0.0,
            x = 0.0,
            tremRatio = 1.0):
    a = {"vfreq" : freq,
         "vlock" : lock,
         "vnoise" : noise,
         "vdelay" : delay,
         "vsens" : sens,
         "vdepth" : depth,
         "vibrato" : 0.0,
         "xPitch" : x,
         "tremRatio" : tremRatio}
    return a
            

def blip(attack = 0.03,
         decay = 0.1,
         depth = 0.0,
         velocity = 0.0):
    return {"blipAttack" : attack,
            "blipDecay" : decay,
            "blipDepth" : depth,
            "blipVelocity" : velocity}

def noise(ratio = 1.0,
          amp = 1.0):
    return {"noiseRatio" : ratio,
            "noiseAmp" : amp}

def chiff(attack = 0.03,
          decay = 0.2,
          velocity = 0.5,
          amp = 1.0):
    a = {"chiffAttack" : attack,
         "chiffDecay" : decay,
         "chiffVelocity" : velocity,
         "chiffAmp" : amp}
    return a
          
def modulator(ratio = 1.0,
              feedback = 0.0,
              lfo = 0.0):
    return {"op4Ratio" : ratio,
            "op4Feedback" : feedback,
            "op4LFO" : lfo}

def carrier(op,
            formant = 1000,
            ratio = 1.0,
            mode = 0,
            velocity = 0.0,
            tremolo = 0.0,
            modDepth = 1.0,
            attack = 0.1,
            decay = 0.2,
            sustain = 1.0,
            release = 0.1,
            lag = 0.0,
            key = 60,
            leftScale = 0,
            rightScale = 0,
            x = 0.0,
            amp = 1.0):
    a = {"op%dFormant" % op : formant,
         "op%dRatio" % op : ratio,
         "op%dMode" % op : mode,
         "op%dVelocity" % op : velocity,
         "op%dTremolo" % op : tremolo,
         "op%dModDepth" % op : modDepth,
         "op%dAttack" % op : attack,
         "op%dDecay" % op : decay,
         "op%dSustain" % op : sustain,
         "op%dRelease" % op : release,
         "op%dModLag" % op : lag,
         "op%dBreakKey" % op : key,
         "op%dLeftKeyScale" % op : leftScale,
         "op%dRightKeyScale" % op : rightScale,
         "op%dAmp" % op : amp,
         "op%dX" % op : x}
    return a

def io(slot, name,
       amp = 0.1,
       vibrato = vibrato(),
       blip = blip(),
       noise = noise(),
       chiff = chiff(),
       modulator = modulator(),
       op1 = carrier(1),
       op2 = carrier(2),
       op3 = carrier(3)):
    p = Io(name)
    p["amp"] = float(amp)
    for d in (vibrato,blip,noise,chiff,modulator,op1,op2,op3):
        for param,val in d.items():
            p[param] = val
    program_bank[slot] = p
    return p

io(0,"Thin Reed",
   amp = 0.141,
   vibrato = vibrato(freq = 4.994,
                     lock = 0,
                     noise = 0.156,
                     sens = 0.050,
                     depth = 0.246,
                     x = 0.000,
                     tremRatio = 1.000),
   blip = blip(attack = 0.076,
               decay = 0.241,
               depth = 0.000,
               velocity = 0.000),
   noise = noise(ratio = 1.000,
                 amp = 0.258),
   chiff = chiff(attack = 0.030,
                 decay = 0.200,
                 velocity = 0.497,
                 amp = 0.979),
   modulator = modulator(ratio = 1.000,
                         feedback = 0.000,
                         lfo = 0.000),
   op1 = carrier(1,
                 formant = 468,
                 ratio = 3.000,
                 mode = 0,
                 velocity = 0.246,
                 tremolo = 0.241,
                 modDepth = 0.400,
                 attack = 0.400,
                 decay = 0.024,
                 sustain = 0.291,
                 release = 0.149,
                 lag = 0.422,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.723),
   op2 = carrier(2,
                 formant = 825,
                 ratio = 2.000,
                 mode = 0,
                 velocity = 0.030,
                 tremolo = 0.000,
                 modDepth = 0.720,
                 attack = 0.064,
                 decay = 0.080,
                 sustain = 0.663,
                 release = 0.091,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 1.000),
   op3 = carrier(3,
                 formant = 1958,
                 ratio = 4.000,
                 mode = 0,
                 velocity = 0.211,
                 tremolo = 0.000,
                 modDepth = 0.720,
                 attack = 0.037,
                 decay = 0.093,
                 sustain = 0.950,
                 release = 0.066,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.480))

io(1,"Tremulus",
   amp = 0.126,
   vibrato = vibrato(freq = 7.104,
                     lock = 1,
                     noise = 0.704,
                     sens = 0.010,
                     depth = 0.201,
                     x = 0.000,
                     tremRatio = 1.000),
   blip = blip(attack = 0.022,
               decay = 0.199,
               depth = 0.000,
               velocity = 0.000),
   noise = noise(ratio = 1.000,
                 amp = 0.136),
   chiff = chiff(attack = 0.030,
                 decay = 0.200,
                 velocity = 0.500,
                 amp = 0.990),
   modulator = modulator(ratio = 2.000,
                         feedback = 0.000,
                         lfo = 0.075),
   op1 = carrier(1,
                 formant = 416,
                 ratio = 1.000,
                 mode = 1,
                 velocity = 0.462,
                 tremolo = 0.065,
                 modDepth = 3.520,
                 attack = 5.581,
                 decay = 1.941,
                 sustain = 1.000,
                 release = 1.155,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.990),
   op2 = carrier(2,
                 formant = 614,
                 ratio = 2.000,
                 mode = 0,
                 velocity = 0.352,
                 tremolo = 0.000,
                 modDepth = 4.640,
                 attack = 5.036,
                 decay = 1.363,
                 sustain = 1.000,
                 release = 4.321,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 1.000),
   op3 = carrier(3,
                 formant = 756,
                 ratio = 6.024,
                 mode = 0,
                 velocity = 0.000,
                 tremolo = 0.000,
                 modDepth = 3.440,
                 attack = 0.769,
                 decay = 1.044,
                 sustain = 0.437,
                 release = 3.996,
                 lag = 0.975,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.658))

io(2,"LongDark",
   amp = 0.126,
   vibrato = vibrato(freq = 7.982,
                     lock = 1,
                     noise = 0.985,
                     sens = 0.025,
                     depth = 0.000,
                     x = 0.000,
                     tremRatio = 1.000),
   blip = blip(attack = 0.080,
               decay = 0.213,
               depth = 0.000,
               velocity = 0.000),
   noise = noise(ratio = 1.000,
                 amp = 0.258),
   chiff = chiff(attack = 0.030,
                 decay = 0.200,
                 velocity = 0.819,
                 amp = 0.506),
   modulator = modulator(ratio = 2.000,
                         feedback = 0.000,
                         lfo = 0.000),
   op1 = carrier(1,
                 formant = 355,
                 ratio = 2.791,
                 mode = 1,
                 velocity = 0.643,
                 tremolo = 0.000,
                 modDepth = 2.640,
                 attack = 0.199,
                 decay = 0.011,
                 sustain = 0.638,
                 release = 0.152,
                 lag = 0.699,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.864),
   op2 = carrier(2,
                 formant = 509,
                 ratio = 1.000,
                 mode = 0,
                 velocity = 0.000,
                 tremolo = 0.000,
                 modDepth = 7.920,
                 attack = 1.016,
                 decay = 1.805,
                 sustain = 0.392,
                 release = 3.724,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.959),
   op3 = carrier(3,
                 formant = 967,
                 ratio = 6.000,
                 mode = 1,
                 velocity = 0.467,
                 tremolo = 0.000,
                 modDepth = 0.160,
                 attack = 0.994,
                 decay = 2.180,
                 sustain = 0.879,
                 release = 2.406,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.149))

io(3,"Callisto",
   amp = 0.355,
   vibrato = vibrato(freq = 4.960,
                     lock = 1,
                     noise = 0.995,
                     sens = 0.045,
                     depth = 0.080,
                     x = 0.000,
                     tremRatio = 1.000),
   blip = blip(attack = 0.005,
               decay = 0.044,
               depth = 0.051,
               velocity = 0.000),
   noise = noise(ratio = 4.000,
                 amp = 0.246),
   chiff = chiff(attack = 0.030,
                 decay = 0.200,
                 velocity = 0.500,
                 amp = 1.000),
   modulator = modulator(ratio = 2.000,
                         feedback = 1.395,
                         lfo = 0.080),
   op1 = carrier(1,
                 formant = 610,
                 ratio = 1.000,
                 mode = 1,
                 velocity = 0.598,
                 tremolo = 0.045,
                 modDepth = 0.480,
                 attack = 0.064,
                 decay = 0.665,
                 sustain = 1.000,
                 release = 0.059,
                 lag = 0.487,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.686),
   op2 = carrier(2,
                 formant = 936,
                 ratio = 2.041,
                 mode = 1,
                 velocity = 0.518,
                 tremolo = 0.000,
                 modDepth = 0.480,
                 attack = 0.009,
                 decay = 0.521,
                 sustain = 1.000,
                 release = 0.262,
                 lag = 0.608,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.528),
   op3 = carrier(3,
                 formant = 1558,
                 ratio = 4.000,
                 mode = 1,
                 velocity = 0.844,
                 tremolo = 0.286,
                 modDepth = 0.400,
                 attack = 0.118,
                 decay = 0.315,
                 sustain = 0.854,
                 release = 0.027,
                 lag = 0.397,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.423))

io(4,"Metis",
   amp = 0.112,
   vibrato = vibrato(freq = 14.404,
                     lock = 1,
                     noise = 0.000,
                     sens = 0.025,
                     depth = 0.256,
                     x = 0.000,
                     tremRatio = 0.500),
   blip = blip(attack = 0.070,
               decay = 0.286,
               depth = 0.000,
               velocity = 0.000),
   noise = noise(ratio = 4.000,
                 amp = 0.373),
   chiff = chiff(attack = 0.030,
                 decay = 0.200,
                 velocity = 0.854,
                 amp = 0.990),
   modulator = modulator(ratio = 2.000,
                         feedback = 0.990,
                         lfo = 0.000),
   op1 = carrier(1,
                 formant = 444,
                 ratio = 4.000,
                 mode = 0,
                 velocity = 0.301,
                 tremolo = 0.005,
                 modDepth = 2.720,
                 attack = 0.043,
                 decay = 0.085,
                 sustain = 1.000,
                 release = 0.044,
                 lag = 0.261,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.990),
   op2 = carrier(2,
                 formant = 630,
                 ratio = 1.000,
                 mode = 0,
                 velocity = 1.000,
                 tremolo = 0.000,
                 modDepth = 1.200,
                 attack = 0.044,
                 decay = 0.032,
                 sustain = 1.000,
                 release = 0.076,
                 lag = 0.819,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.990),
   op3 = carrier(3,
                 formant = 1811,
                 ratio = 2.000,
                 mode = 1,
                 velocity = 0.960,
                 tremolo = 0.000,
                 modDepth = 0.960,
                 attack = 0.018,
                 decay = 0.011,
                 sustain = 1.000,
                 release = 0.004,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.846))

io(5,"Adrastea",
   amp = 0.200,
   vibrato = vibrato(freq = 12.000,
                     lock = 1,
                     noise = 0.000,
                     sens = 0.050,
                     depth = 0.739,
                     x = 0.000,
                     tremRatio = 0.250),
   blip = blip(attack = 0.026,
               decay = 0.133,
               depth = 0.000,
               velocity = 0.000),
   noise = noise(ratio = 1.000,
                 amp = 0.381),
   chiff = chiff(attack = 0.030,
                 decay = 0.200,
                 velocity = 0.497,
                 amp = 0.446),
   modulator = modulator(ratio = 2.000,
                         feedback = 0.000,
                         lfo = 0.231),
   op1 = carrier(1,
                 formant = 341,
                 ratio = 4.000,
                 mode = 1,
                 velocity = 0.568,
                 tremolo = 0.000,
                 modDepth = 5.360,
                 attack = 0.140,
                 decay = 0.123,
                 sustain = 0.673,
                 release = 0.180,
                 lag = 0.694,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.811),
   op2 = carrier(2,
                 formant = 536,
                 ratio = 8.000,
                 mode = 1,
                 velocity = 0.206,
                 tremolo = 0.000,
                 modDepth = 0.640,
                 attack = 0.040,
                 decay = 0.101,
                 sustain = 0.648,
                 release = 0.008,
                 lag = 0.417,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 1.000),
   op3 = carrier(3,
                 formant = 807,
                 ratio = 4.000,
                 mode = 0,
                 velocity = 0.744,
                 tremolo = 0.266,
                 modDepth = 3.600,
                 attack = 0.039,
                 decay = 0.651,
                 sustain = 0.834,
                 release = 0.553,
                 lag = 0.583,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.406))

io(6,"Amalthea",
   amp = 0.126,
   vibrato = vibrato(freq = 3.658,
                     lock = 1,
                     noise = 0.000,
                     sens = 0.080,
                     depth = 0.739,
                     x = 0.000,
                     tremRatio = 1.000),
   blip = blip(attack = 0.296,
               decay = 0.258,
               depth = 0.000,
               velocity = 0.000),
   noise = noise(ratio = 1.000,
                 amp = 0.381),
   chiff = chiff(attack = 0.030,
                 decay = 0.200,
                 velocity = 0.500,
                 amp = 0.990),
   modulator = modulator(ratio = 1.000,
                         feedback = 0.000,
                         lfo = 0.186),
   op1 = carrier(1,
                 formant = 564,
                 ratio = 5.000,
                 mode = 0,
                 velocity = 0.191,
                 tremolo = 0.000,
                 modDepth = 0.560,
                 attack = 0.597,
                 decay = 1.061,
                 sustain = 0.694,
                 release = 4.989,
                 lag = 0.271,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.939),
   op2 = carrier(2,
                 formant = 914,
                 ratio = 4.000,
                 mode = 1,
                 velocity = 0.000,
                 tremolo = 0.000,
                 modDepth = 1.760,
                 attack = 1.323,
                 decay = 1.225,
                 sustain = 0.568,
                 release = 7.474,
                 lag = 0.015,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.528),
   op3 = carrier(3,
                 formant = 1368,
                 ratio = 0.186,
                 mode = 1,
                 velocity = 0.769,
                 tremolo = 0.000,
                 modDepth = 1.040,
                 attack = 1.881,
                 decay = 2.406,
                 sustain = 0.553,
                 release = 2.364,
                 lag = 0.744,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.990))

io(7,"Leda",
   amp = 0.251,
   vibrato = vibrato(freq = 7.854,
                     lock = 1,
                     noise = 0.000,
                     sens = 0.090,
                     depth = 0.045,
                     x = 0.000,
                     tremRatio = 1.000),
   blip = blip(attack = 0.098,
               decay = 0.157,
               depth = 0.000,
               velocity = 0.000),
   noise = noise(ratio = 2.000,
                 amp = 0.568),
   chiff = chiff(attack = 0.058,
                 decay = 0.200,
                 velocity = 0.500,
                 amp = 1.000),
   modulator = modulator(ratio = 2.000,
                         feedback = 0.000,
                         lfo = 0.000),
   op1 = carrier(1,
                 formant = 346,
                 ratio = 2.005,
                 mode = 0,
                 velocity = 0.548,
                 tremolo = 0.000,
                 modDepth = 3.840,
                 attack = 0.133,
                 decay = 0.048,
                 sustain = 1.000,
                 release = 0.263,
                 lag = 0.196,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.118),
   op2 = carrier(2,
                 formant = 865,
                 ratio = 5.000,
                 mode = 1,
                 velocity = 0.301,
                 tremolo = 0.000,
                 modDepth = 0.720,
                 attack = 0.132,
                 decay = 0.094,
                 sustain = 1.000,
                 release = 0.099,
                 lag = 0.774,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 1.000),
   op3 = carrier(3,
                 formant = 1494,
                 ratio = 4.775,
                 mode = 1,
                 velocity = 0.849,
                 tremolo = 0.000,
                 modDepth = 2.560,
                 attack = 0.062,
                 decay = 0.022,
                 sustain = 0.694,
                 release = 0.262,
                 lag = 0.377,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.156))

io(8,"Dia",
   amp = 0.398,
   vibrato = vibrato(freq = 7.097,
                     lock = 1,
                     noise = 0.000,
                     sens = 0.020,
                     depth = 0.236,
                     x = 0.000,
                     tremRatio = 1.000),
   blip = blip(attack = 0.001,
               decay = 0.022,
               depth = 0.360,
               velocity = 0.000),
   noise = noise(ratio = 4.000,
                 amp = 0.094),
   chiff = chiff(attack = 0.000,
                 decay = 0.403,
                 velocity = 0.000,
                 amp = 0.258),
   modulator = modulator(ratio = 4.000,
                         feedback = 0.000,
                         lfo = 0.000),
   op1 = carrier(1,
                 formant = 441,
                 ratio = 4.019,
                 mode = 0,
                 velocity = 0.653,
                 tremolo = 0.000,
                 modDepth = 6.160,
                 attack = 0.000,
                 decay = 1.030,
                 sustain = 0.060,
                 release = 0.104,
                 lag = 0.583,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.461),
   op2 = carrier(2,
                 formant = 795,
                 ratio = 6.900,
                 mode = 1,
                 velocity = 1.000,
                 tremolo = 0.000,
                 modDepth = 0.640,
                 attack = 0.000,
                 decay = 3.870,
                 sustain = 0.000,
                 release = 2.406,
                 lag = 0.628,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.708),
   op3 = carrier(3,
                 formant = 1383,
                 ratio = 1.000,
                 mode = 1,
                 velocity = 0.714,
                 tremolo = 0.000,
                 modDepth = 0.480,
                 attack = 0.000,
                 decay = 2.406,
                 sustain = 0.000,
                 release = 0.705,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.900))

io(9,"Marius",
   amp = 0.112,
   vibrato = vibrato(freq = 6.583,
                     lock = 1,
                     noise = 0.472,
                     sens = 0.377,
                     depth = 0.000,
                     x = 0.000,
                     tremRatio = 0.750),
   blip = blip(attack = 0.707,
               decay = 0.298,
               depth = 0.002,
               velocity = 0.000),
   noise = noise(ratio = 3.000,
                 amp = 0.163),
   chiff = chiff(attack = 0.030,
                 decay = 0.200,
                 velocity = 0.995,
                 amp = 1.000),
   modulator = modulator(ratio = 1.000,
                         feedback = 0.000,
                         lfo = 0.080),
   op1 = carrier(1,
                 formant = 128,
                 ratio = 2.000,
                 mode = 0,
                 velocity = 0.000,
                 tremolo = 0.000,
                 modDepth = 3.360,
                 attack = 0.718,
                 decay = 0.805,
                 sustain = 0.000,
                 release = 3.432,
                 lag = 0.146,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 1.000),
   op2 = carrier(2,
                 formant = 229,
                 ratio = 1.000,
                 mode = 0,
                 velocity = 0.286,
                 tremolo = 0.000,
                 modDepth = 1.920,
                 attack = 5.258,
                 decay = 0.419,
                 sustain = 0.020,
                 release = 1.935,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 1.000),
   op3 = carrier(3,
                 formant = 1267,
                 ratio = 3.000,
                 mode = 1,
                 velocity = 0.000,
                 tremolo = 0.492,
                 modDepth = 0.160,
                 attack = 1.956,
                 decay = 1.108,
                 sustain = 1.000,
                 release = 1.923,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 1.000))

io(10,"Themisto",
   amp = 0.100,
   vibrato = vibrato(freq = 3.838,
                     lock = 1,
                     noise = 0.447,
                     sens = 0.010,
                     depth = 0.000,
                     x = 0.000,
                     tremRatio = 1.000),
   blip = blip(attack = 0.064,
               decay = 0.605,
               depth = 0.036,
               velocity = 0.000),
   noise = noise(ratio = 2.000,
                 amp = 0.019),
   chiff = chiff(attack = 0.030,
                 decay = 0.200,
                 velocity = 0.497,
                 amp = 0.000),
   modulator = modulator(ratio = 1.000,
                         feedback = 0.900,
                         lfo = 0.417),
   op1 = carrier(1,
                 formant = 379,
                 ratio = 1.000,
                 mode = 0,
                 velocity = 0.683,
                 tremolo = 0.899,
                 modDepth = 3.920,
                 attack = 1.284,
                 decay = 0.771,
                 sustain = 0.658,
                 release = 8.886,
                 lag = 0.774,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 1.000),
   op2 = carrier(2,
                 formant = 822,
                 ratio = 4.000,
                 mode = 1,
                 velocity = 0.291,
                 tremolo = 0.000,
                 modDepth = 0.480,
                 attack = 1.419,
                 decay = 0.818,
                 sustain = 0.367,
                 release = 3.371,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 1.000),
   op3 = carrier(3,
                 formant = 1817,
                 ratio = 2.000,
                 mode = 1,
                 velocity = 0.000,
                 tremolo = 0.000,
                 modDepth = 2.880,
                 attack = 1.467,
                 decay = 1.147,
                 sustain = 0.523,
                 release = 2.722,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.038))

io(11,"Himalia",
   amp = 0.282,
   vibrato = vibrato(freq = 6.986,
                     lock = 1,
                     noise = 0.884,
                     sens = 0.015,
                     depth = 0.000,
                     x = 0.000,
                     tremRatio = 1.333),
   blip = blip(attack = 0.012,
               decay = 0.247,
               depth = 0.000,
               velocity = 0.000),
   noise = noise(ratio = 2.000,
                 amp = 0.295),
   chiff = chiff(attack = 0.055,
                 decay = 0.200,
                 velocity = 0.500,
                 amp = 1.000),
   modulator = modulator(ratio = 2.000,
                         feedback = 1.530,
                         lfo = 0.000),
   op1 = carrier(1,
                 formant = 299,
                 ratio = 3.000,
                 mode = 0,
                 velocity = 0.387,
                 tremolo = 0.000,
                 modDepth = 7.680,
                 attack = 0.000,
                 decay = 1.953,
                 sustain = 1.000,
                 release = 0.024,
                 lag = 0.412,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.362),
   op2 = carrier(2,
                 formant = 1345,
                 ratio = 3.000,
                 mode = 1,
                 velocity = 0.889,
                 tremolo = 0.000,
                 modDepth = 1.040,
                 attack = 0.031,
                 decay = 0.003,
                 sustain = 1.000,
                 release = 0.006,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 1.000),
   op3 = carrier(3,
                 formant = 3446,
                 ratio = 6.000,
                 mode = 1,
                 velocity = 0.000,
                 tremolo = 0.000,
                 modDepth = 0.880,
                 attack = 0.007,
                 decay = 1.486,
                 sustain = 1.000,
                 release = 0.059,
                 lag = 0.286,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.094))

io(12,"Lysithea",
   amp = 0.112,
   vibrato = vibrato(freq = 4.022,
                     lock = 0,
                     noise = 0.568,
                     sens = 0.050,
                     depth = 0.121,
                     x = 0.000,
                     tremRatio = 1.000),
   blip = blip(attack = 0.031,
               decay = 0.107,
               depth = 0.000,
               velocity = 0.000),
   noise = noise(ratio = 1.000,
                 amp = 0.562),
   chiff = chiff(attack = 0.030,
                 decay = 0.200,
                 velocity = 0.500,
                 amp = 1.000),
   modulator = modulator(ratio = 2.000,
                         feedback = 0.000,
                         lfo = 0.000),
   op1 = carrier(1,
                 formant = 291,
                 ratio = 3.000,
                 mode = 1,
                 velocity = 0.668,
                 tremolo = 0.000,
                 modDepth = 2.000,
                 attack = 2.346,
                 decay = 1.979,
                 sustain = 0.869,
                 release = 5.416,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.693),
   op2 = carrier(2,
                 formant = 393,
                 ratio = 2.000,
                 mode = 0,
                 velocity = 0.467,
                 tremolo = 0.000,
                 modDepth = 3.120,
                 attack = 2.293,
                 decay = 0.664,
                 sustain = 0.709,
                 release = 1.749,
                 lag = 0.211,
                 key = 60,
                 leftScale = +3,
                 rightScale = +0,
                 x = 0.000,
                 amp = 1.000),
   op3 = carrier(3,
                 formant = 1918,
                 ratio = 1.000,
                 mode = 0,
                 velocity = 0.000,
                 tremolo = 0.000,
                 modDepth = 3.840,
                 attack = 0.053,
                 decay = 0.057,
                 sustain = 0.603,
                 release = 0.193,
                 lag = 0.000,
                 key = 60,
                 leftScale = +3,
                 rightScale = +0,
                 x = 0.000,
                 amp = 1.000))

io(13,"Elera",
   amp = 0.126,
   vibrato = vibrato(freq = 4.022,
                     lock = 0,
                     noise = 0.568,
                     sens = 0.050,
                     depth = 0.121,
                     x = 0.000,
                     tremRatio = 1.000),
   blip = blip(attack = 0.031,
               decay = 0.107,
               depth = 0.020,
               velocity = 0.000),
   noise = noise(ratio = 3.000,
                 amp = 0.130),
   chiff = chiff(attack = 0.030,
                 decay = 0.200,
                 velocity = 0.500,
                 amp = 0.533),
   modulator = modulator(ratio = 2.000,
                         feedback = 0.000,
                         lfo = 0.000),
   op1 = carrier(1,
                 formant = 291,
                 ratio = 5.000,
                 mode = 0,
                 velocity = 0.000,
                 tremolo = 0.000,
                 modDepth = 2.000,
                 attack = 0.000,
                 decay = 1.979,
                 sustain = 1.000,
                 release = 0.000,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.658),
   op2 = carrier(2,
                 formant = 683,
                 ratio = 2.000,
                 mode = 1,
                 velocity = 0.000,
                 tremolo = 0.000,
                 modDepth = 2.160,
                 attack = 0.001,
                 decay = 0.664,
                 sustain = 1.000,
                 release = 0.016,
                 lag = 0.211,
                 key = 60,
                 leftScale = +3,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.990),
   op3 = carrier(3,
                 formant = 2058,
                 ratio = 1.000,
                 mode = 1,
                 velocity = 0.000,
                 tremolo = 0.000,
                 modDepth = 2.880,
                 attack = 0.002,
                 decay = 0.057,
                 sustain = 0.719,
                 release = 0.007,
                 lag = 0.000,
                 key = 60,
                 leftScale = +3,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.990))

io(14,"Carpo",
   amp = 0.141,
   vibrato = vibrato(freq = 4.022,
                     lock = 0,
                     noise = 0.568,
                     sens = 0.050,
                     depth = 0.281,
                     x = 0.000,
                     tremRatio = 1.500),
   blip = blip(attack = 0.031,
               decay = 0.107,
               depth = 0.020,
               velocity = 0.000),
   noise = noise(ratio = 3.000,
                 amp = 0.000),
   chiff = chiff(attack = 0.030,
                 decay = 0.200,
                 velocity = 0.500,
                 amp = 0.000),
   modulator = modulator(ratio = 2.000,
                         feedback = 0.495,
                         lfo = 0.000),
   op1 = carrier(1,
                 formant = 3071,
                 ratio = 4.019,
                 mode = 0,
                 velocity = 0.000,
                 tremolo = 0.000,
                 modDepth = 4.400,
                 attack = 0.133,
                 decay = 1.979,
                 sustain = 1.000,
                 release = 0.250,
                 lag = 0.000,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.377),
   op2 = carrier(2,
                 formant = 592,
                 ratio = 2.000,
                 mode = 1,
                 velocity = 0.322,
                 tremolo = 0.417,
                 modDepth = 2.640,
                 attack = 0.104,
                 decay = 0.664,
                 sustain = 1.000,
                 release = 1.295,
                 lag = 0.211,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.979),
   op3 = carrier(3,
                 formant = 1758,
                 ratio = 1.000,
                 mode = 1,
                 velocity = 0.402,
                 tremolo = 0.477,
                 modDepth = 3.040,
                 attack = 0.913,
                 decay = 0.057,
                 sustain = 0.719,
                 release = 2.353,
                 lag = 0.739,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.043))

io(15,"Euporie",
   amp = 0.112,
   vibrato = vibrato(freq = 7.473,
                     lock = 1,
                     noise = 0.000,
                     sens = 0.045,
                     depth = 0.291,
                     x = 0.000,
                     tremRatio = 1.000),
   blip = blip(attack = 0.011,
               decay = 0.120,
               depth = 0.021,
               velocity = 0.000),
   noise = noise(ratio = 6.000,
                 amp = 0.715),
   chiff = chiff(attack = 0.030,
                 decay = 0.200,
                 velocity = 0.500,
                 amp = 1.000),
   modulator = modulator(ratio = 3.000,
                         feedback = 3.000,
                         lfo = 0.000),
   op1 = carrier(1,
                 formant = 129,
                 ratio = 1.000,
                 mode = 1,
                 velocity = 0.462,
                 tremolo = 0.000,
                 modDepth = 1.520,
                 attack = 0.932,
                 decay = 0.817,
                 sustain = 0.497,
                 release = 1.957,
                 lag = 0.487,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 1.000),
   op2 = carrier(2,
                 formant = 416,
                 ratio = 5.046,
                 mode = 1,
                 velocity = 0.226,
                 tremolo = 0.000,
                 modDepth = 0.800,
                 attack = 0.512,
                 decay = 2.053,
                 sustain = 0.774,
                 release = 3.668,
                 lag = 0.598,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 1.000),
   op3 = carrier(3,
                 formant = 786,
                 ratio = 1.000,
                 mode = 1,
                 velocity = 0.000,
                 tremolo = 0.000,
                 modDepth = 0.240,
                 attack = 2.345,
                 decay = 0.462,
                 sustain = 0.688,
                 release = 4.316,
                 lag = 0.347,
                 key = 60,
                 leftScale = +0,
                 rightScale = +0,
                 x = 0.000,
                 amp = 0.693))

