# ****************************************************************
# THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT MANUALLY
# ****************************************************************

print("Importing instrumental synths:")
import llia.synths.ss1.ss1_proxy    
import llia.synths.saw3.s3_proxy
import llia.synths.orgn.orgn_proxy
import llia.synths.masa.masa_proxy
import llia.synths.klstr.klstr_proxy
import llia.synths.klstr2.klstr2_proxy
import llia.synths.rdrum.rdrum_proxy
import llia.synths.fm2.fm2_proxy
import llia.synths.algo.algo_proxy
import llia.synths.io.io_proxy    
import llia.synths.corvus.corvus_proxy
import llia.synths.m.m_proxy        
import llia.synths.sol.sol_proxy
# END SYNTH IMPORTS

print("Importing effects:")
import llia.synths.carnal.crnl_proxy
import llia.synths.flngr.flngr_proxy
import llia.synths.tremolo.trm_proxy
import llia.synths.mixer.mixer_proxy
import llia.synths.panner.panner_proxy
import llia.synths.asplit.asplit_proxy
import llia.synths.rumklang.rumklang_proxy
import llia.synths.chronos.chronos_proxy
import llia.synths.pitchshifter.pitchshifter_proxy
import llia.synths.ringmodulator.rm_proxy
import llia.synths.crusher.crusher_proxy
import llia.synths.hund.hund_proxy
import llia.synths.qmod.qmod_proxy
import llia.synths.bandpass.bandpass_proxy
import llia.synths.notch.notch_proxy
import llia.synths.prism.prism_proxy
import llia.synths.formant.formant_proxy
import llia.synths.xover.xover_proxy
import llia.synths.comb.comb_proxy
import llia.synths.scanner.scanner_proxy
# END EFX IMPORTS

print("Importing controller synths:")
import llia.synths.lfo1.lfo1_proxy
import llia.synths.lfo2.lfo2_proxy
import llia.synths.lfo3.lfo3_proxy
import llia.synths.cascade.cascade_proxy
import llia.synths.snh.snh_proxy
import llia.synths.ghostbus.ghost_proxy
import llia.synths.controlmixer.controlmixer_proxy
import llia.synths.cutil.cutil_proxy
import llia.synths.envgen.envgen_proxy
# END CONTROLLER IMPORTS
