#! /usr/bin/python

import sys
from argparse import ArgumentParser
from os import makedirs, environ, listdir
from os.path import exists, join, split, expanduser, abspath
import scd,graphics,sproxy,sdata,spp,srandom,stkeditor
from file_util import replace_lines


USAGE=\
"""
addsynth --name name [options]

    Creates boilerplate files for adding new synth to Llia.

    OPTIONS:

    --name <name>
         The synth name.  If a synth with the same name already exists
         an error message is displayed and the script terminates.
         
         A SYNTH NAME MUST BE SPECIFIED!

    --stype <type>
         Sets synth type, must be one of 'synth', 'efx' or 'controller'
         The default is 'synth', a playable instrument.

   --d <path> or --dev <path>
        Sets path to Llia development directory.
        If an explicit path is not specified via --dev
        the environmental variable LLIADEV is checked.
        If LLIADEV is not defined the path is determined
        heuristically by using the parent of the current 
        directory.     

  --P <file> or --params <file>
        Specify optional synth parameter file.

        The parameter file has a simple format with each parameter
        on a separate line.  Blank lines and lines beginning with '#'
        are ignored.  Each parameter has three components separated
        by spaces:
                         t param value

        Where: t is the data type, either 'f' (float)  or 'i' (int).
               param is the synth parameter.
               value is the default value.

        If a param file is specified several of the generated objects
        will automatically contain parameter deceleration/initialization.

    -l or --list
        Produce list of files that will be produced without actually 
        creating anything.
"""   


def usage():
    print USAGE

def _get_development_path():
    from os import environ
    
def synth_directories_exists(devdir, sname):
    sdir = join(devdir,"llia","synths",sname.lower())
    return (exists(sdir), sdir)

def _update_manifest(devdir,stype,sname):
    sname = sname.lower()
    mfile = join(devdir,'llia','manifest.py')
    acc = 'import llia.synths.%s.%s_proxy' % (sname,sname)
    target = {"efx" : "# END EFX IMPORTS",
              "controller" : "# END CONTROLLER IMPORTS",
              "synth" : "# END SYNTH IMPORTS"}[stype]
    payload = [acc,target]
    replace_lines(mfile,target,payload)

def _validate_stype(stype):
    if stype is None:
        return "synth"
    else:
        stype = stype.lower()
        if stype not in ("efx","controller","synth"):
            msg = "Invalid synth type: '%s'" % stype
            raise ValueError(msg)
        return stype

def create_synth(devdir, stype, sname, params=[]):
    devdir = expanduser(devdir)
    flg, path = synth_directories_exists(devdir,sname)
    stype = _validate_stype(stype)
    if flg:
        msg = "Cowardly refusing to overwrite existing Llia synth: '%s'"
        msg = msg % path
        raise IOError(msg)
    else:
        print "**** Creating %s Files ****" % sname
        #sname = sname.lower()
        makedirs(join(devdir,"resources",sname.lower()))
        makedirs(join(devdir,"llia","synths",sname.lower(),"tk"))
        scd.write_synthdef(devdir,sname,params)
        graphics.copy_graphic_templates(devdir,sname)
        sproxy.write_synth_proxy_file(devdir,stype,sname)
        sdata.write_synth_data_file(devdir,sname,params)
        spp.write_pp_file(devdir,sname,params)
        srandom.write_random_generator_file(devdir,sname)
        stkeditor.write_editor_file(devdir,sname)
        _update_manifest(devdir,stype,sname)

def _get_dev_path(arg):
    if arg:
        return arg
    else:
        try:
            dev = environ["LLIADEV"]
            return dev
        except KeyError:
            cwd = abspath(__file__)
            cwd = split(cwd)[0]
            return split(cwd)[0]

def _read_param_file(arg):
    if arg is None:
        return []
    else:
        arg = expanduser(arg)
        acc = []
        try:
            fobj = open(arg,'r')
            lines = fobj.readlines()
            fobj.close()
            counter = 0
            for line in lines:
                line = line.strip()
                counter += 1
                bcc = []
                for f in line.split():
                    bcc.append(f.strip())
                if line.startswith("#") or not bcc:
                    pass
                else:
                    if len(bcc) != 3:
                        msg = "Invalid param syntax: line %d, '%s'" % (counter, line)
                        raise ValueError(msg)
                    else:
                        acc.append(bcc)
        except IOError:
            msg = "Can not open synth paranmeter file: '%s'" % arg
            raise IOError(msg)
        return acc


# def list_files(devdir,stype,sname):
#     sname = sname.lower()
#     pad = ' '*4
#     print "New files:"
#     print pad,join(devdir,'sc','SynthDefs','%s.scd' % sname)
#     for f in ('_proxy','_data','_pp','_random'):
#         print pad,join(devdir,'llia','synths',sname,'%s%s.py' % (sname,f))
#     print pad,join(devdir,'llia','synths',sname,'tk','editor.py')
#     print "Modified files:"
#     print pad,join(devdir,'s','LliaHandler','install_synths.scd')
#     print pad,join(devdir,'llia','manifest.py')
#     print "Copied graphic files:"
#     g = join(devdir,"tools","templates","graphics")
#     r = join(devdir,"resources",sname)
#     for f in sorted(listdir(g)):
#         print pad,join(r,f)
    
    
if __name__ == '__main__':
    parser = ArgumentParser(description="Reduce the pain of adding a synth to Llia")
    parser.add_argument('-d','--dev')
    parser.add_argument('-p','--params')
    parser.add_argument('-u','--usage', action="store_true")
    parser.add_argument('--stype')
    parser.add_argument('--name')
    parser.add_argument('-t','--list',action="store_true")
    args = parser.parse_args()
    if args.usage:
        usage()
        sys.exit()
    devdir = _get_dev_path(args.dev)
    params = _read_param_file(args.params)
    sname = args.name
    stype = _validate_stype(args.stype)
    if not sname:
        print "A Synth name must be specified."
        print "Try --usage for help"
        sys.exit()
    # if args.list:
    #     list_files(devdir,stype,sname)
    #     sys.exit()
    print "Llia developemenrt directory: '%s'" % devdir
    print "Params specified: %d" % len(params)
    create_synth(devdir,stype,sname,params)
