# llia.synths.klstr2.constants

LFO_RATIOS = (1/8.0,
              1/4.0,
              1/3.0,
              1/2.0,
              2/3.0,
              3/4.0,
              1.0,
              5/4.0,
              4/3.0,
              3/2.0,
              5/3.0,
              7/4.0,
              2.0, 2.5,
              3.0, 4.0, 5.0, 6.0, 8.0)

MAX_ENV_SEGMENT_TIME = 12
CLUSTER_RANGE = (0,1)

HARMONICS = [1,2,3,4,6,8,12,16,24,32,48,64]
HARMONIC_COUNT_RANGE = (HARMONICS[0],HARMONICS[-1])
#HARMONIC_MOD_RANGE = (-HARMONIC_COUNT_RANGE[1],HARMONIC_COUNT_RANGE[1])
HARMONIC_MOD_RANGE = [0]+HARMONICS

acc = []
for r in HARMONICS:
    acc.append(-r)
acc.append(0)
POLAR_HARMONIC_MOD_RANGE = acc + HARMONICS

FILTER_FREQUENCIES = [67,125,250,500,1000,2000,4000,8000,16000]
NOISE_LOWPASS_FREQUENCIES = FILTER_FREQUENCIES
NOISE_HIGHPASS_FREQUENCIES = NOISE_LOWPASS_FREQUENCIES
NOISE_FILTER_MOD_RANGE = [0]+NOISE_LOWPASS_FREQUENCIES


LOWPASS_RANGE = (FILTER_FREQUENCIES[0],FILTER_FREQUENCIES[-1])
HIGHPASS_RANGE = LOWPASS_RANGE
FILTER_MOD_RANGE = (-LOWPASS_RANGE[1],LOWPASS_RANGE[1])

acc = []
for r in FILTER_FREQUENCIES:
    acc.append(-r)
acc.append(0)
FILTER_MOD_VALUES = acc+FILTER_FREQUENCIES


NEGATIVE_FILL_COLOR = "#380407"
POSITIVE_FILL_COLOR = "black"
NORMAL_MOD_DEPTH_COLOR = None
MODERATE_MOD_DEPTH_COLOR = "orange"
DEEP_MOD_DEPTH_COLOR = "yellow"
